paths:
  raw_data_dir: data/raw
  processed_data_dir: data/processed

preprocess:
  ewma_alpha: 0.2
  hampel_window_size: 25
  hampel_sigma_factor: 3
  velocity_threshold_ref_mode: 0.01
  still_window: 5
  window_size: 50
  stride_length: 1
  default_scale: 1.0

logging:
  level: INFO

output_root: data/processed
raw_root: data/raw
compression: lzf
split_ratios:
  train: 0.7
  val: 0.15
  test: 0.15
synthetic_depth_rhos:
  - 0.75
  - 0.5

triplet:
  window_size: 50
  stride: 2
  batch_size: 16
  learning_rate: 0.0001
  epochs: 15

reference:
  window_size: 50
  stride: 2
  energy_threshold_deg: 5.0

thresholds:
  sim: 0.72
  margin: 0.10
  joint: 0.20
  ROM: 0.90
  tempo: 0.30
  drop: 0.62
  k_confirm: 2
  n_drop: 3



class Landmark(IntEnum):
    """MediaPipe landmark indices (33‑point full body)."""

    HEAD = 0  # NOSE
    L_EYE_INNER = 1
    L_EYE = 2
    L_EYE_OUTER = 3
    R_EYE_INNER = 4
    R_EYE = 5
    R_EYE_OUTER = 6
    L_EAR = 7
    R_EAR = 8
    MOUTH_L = 9
    MOUTH_R = 10
    LSH = 11; RSH = 12
    LEL = 13; REL = 14
    LWR = 15; RWR = 16
    L_PINKY = 17; R_PINKY = 18
    L_INDEX = 19; R_INDEX = 20
    L_THUMB = 21; R_THUMB = 22
    LHIP = 23; RHIP = 24
    LKNE = 25; RKNE = 26
    LANK = 27; RANK = 28
    L_HEEL = 29; R_HEEL = 30
    L_FOOT = 31; R_FOOT = 32


# ─────────────────────────────────────────────────────────────────────────────
#  Joint label lists
# ─────────────────────────────────────────────────────────────────────────────

JOINT_LABELS: List[str] = [
    "Head",
    "L_Shoulder",
    "R_Shoulder",
    "L_Elbow",
    "R_Elbow",
    "L_Wrist",
    "R_Wrist",
    "L_Hip",
    "R_Hip",
    "L_Knee",
    "R_Knee",
    "L_Ankle",
    "R_Ankle",
    "L_Foot",
    "R_Foot",
]


@dataclass(frozen=True)
class CameraSettings:
    # Resolutions & frame‑rate
    COLOR_RES: Tuple[int, int] = (848, 480)
    DEPTH_RES: Tuple[int, int] = (848, 480)
    FPS: int = 30

    # Filter parameters
    SPATIAL_MAGNITUDE: float = 3.0
    SPATIAL_ALPHA: float = 0.4
    SPATIAL_DELTA: float = 35.0

    TEMPORAL_ALPHA: float = 0.3
    TEMPORAL_DELTA: float = 100.0

    # Depth clipping (Z‑Threshold)
    MIN_Z_M: float = 1.0
    MAX_Z_M: float = 3.5

    HOLE_FILLING: int = 2  # level 0‑2

    LASER_POWER: float = 300.0

    JOINT_CONFIDENCE_THRESHOLD: float = 0.7

    # ── Enable/disable stages ───────────────
    ENABLE_ALIGN_TO_COLOR: bool = True
    ENABLE_SPATIAL_FILTER: bool = True
    ENABLE_TEMPORAL_FILTER: bool = True
    ENABLE_HOLE_FILLING: bool = True
    ENABLE_Z_CLIP: bool = True
    ENABLE_EMITTER: bool = True


CAMERA = CameraSettings()

# ─────────────────────────────────────────────────────────────────────────────
#  MediaPipe global settings
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class MediaPipeSettings:
    STATIC_MODE: bool = False
    MODEL_COMPLEXITY: int = 1
    SMOOTH_LANDMARKS: bool = True
    MIN_DET_CONF: float = 0.8
    MIN_TRK_CONF: float = 0.95
    VISIBILITY_THRESHOLD: float = 0.8


MP = MediaPipeSettings()
